name: Synthapse Frontend 

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  Domain: 'synthapse.io'
  BUCKET: 'synthapse'
  ENVIRONMENT: true

jobs:

  build:
    # needs: E2E
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build and deploy frontend to static GCP Cloud Storage
        run: |
          cd ./landing/
          npm install --force
          CI=false npm run build
          gsutil web set -m index.html -e index.html gs://${{ env.BUCKET }}
          gsutil iam ch allUsers:legacyObjectReader gs://${{ env.BUCKET }}
          gsutil -h "Cache-Control:public, max-age=0, no-transform" rsync -d -r ./build gs://${{env.BUCKET}}
        # gcloud compute url-maps invalidate-cdn-cache planfi-lb --path '/${{env.Domain}}/*'